CREATE or REPLACE VIEW ATRIBUTE_VIEW (NUME_ATRIBUT, ID_ATRIBUT, NUME_CATEGORIE_ATRIBUT, ID_CATEGORIE_ATRIBUT) AS
select a.nume AS NUME_ATRIBUT, a.id AS ID_ATRIBUT, ca.nume AS NUME_CATEGORIE_ATRIBUT, ca.id AS ID_CATEGORIE_ATRIBUT
	from atribute a, categorii_ale_atributelor ca
	where a.id_categorii_ale_atributelor = ca.id;

CREATE or REPLACE VIEW PRODUSE_ATRIBUTE_VIEW (NUME_PRODUS, ID_PRODUS, NUME_ATRIBUT, ID_ATRIBUT, NUME_CATEGORIE_ATRIBUT, ID_CATEGORIE_ATRIBUT) AS
select p.nume AS NUME_PRODUS , p.id AS ID_PRODUS, a.NUME_ATRIBUT AS NUME_ATRIBUT, a.ID_ATRIBUT AS ID_ATRIBUT, a.NUME_CATEGORIE_ATRIBUT AS NUME_CATEGORIE_ATRIBUT, a.ID_CATEGORIE_ATRIBUT AS ID_CATEGORIE_ATRIBUT 
	from produse p, atribute_produse ap, ATRIBUTE_VIEW a
	where p.id=ap.id_prod AND a.ID_ATRIBUT=ap.id_atribut;

CREATE or REPLACE VIEW PRODUSE_ETALOANE_VIEW (NUME_PRODUS, ID_PRODUS, NUME_ETALON, ID_ETALON) AS
select p.nume as NUME_PRODUS, p.id AS ID_PRODUS, e.nume AS NUME_ETALON, e.id AS ID_ETALON  
	from etaloane e, etaloane_produse ep, produse p
	where p.id=ep.id_prod AND e.id=ep.id_etalon;
	
CREATE or REPLACE VIEW PRODUSE_CATEGORII_VIEW (NUME_PRODUS, ID_PRODUS, PRET_PRODUS, CANTITATE_PRODUS, DATA_INREG, NUME_CATEGORIE, ID_CATEGORIE) AS
select p.nume as NUME_PRODUS, p.id AS ID_PRODUS, p.pret as PRET_PRODUS, p.cantitate AS CANTITATE_PRODUS, p.data_inreg AS DATA_INREG, c.nume AS NUME_CATEGORIE, c.id as ID_CATEGORIE
	from produse p, categorii_produse cp, categorii c
	where p.id=cp.id_prod AND c.id=cp.id_cat;

CREATE or REPLACE VIEW PRODUSE_PRODUCATORI_VIEW (NUME_PRODUS, ID_PRODUS, NUME_PRODUCATOR, ID_PRODUCATOR) AS
select p.nume AS NUME_PRODUS, p.id AS ID_PRODUS, prod.nume AS NUME_PRODUCATOR, prod.id AS ID_PRODUCATOR
	from produse p, producatori_produse pp, producatori prod
	where p.id=pp.id_produs AND prod.id=pp.id_producator;
	
CREATE or REPLACE VIEW PRODUS_VIEW (NUME_PRODUS, ID_PRODUS, PRET_PRODUS, CANTITATE_PRODUS, NUME_ATRIBUT, ID_ATRIBUT, NUME_CATEGORIE_ATRIBUT, ID_CATEGORIE_ATRIBUT,NUME_ETALON, ID_ETALON, NUME_CATEGORIE, ID_CATEGORIE, NUME_PRODUCATOR, ID_PRODUCATOR, NUME_POZA, ID_POZA, DESCRIERE_POZA, ID) AS 
select PRODUSE_CATEGORII_VIEW.NUME_PRODUS, PRODUSE_CATEGORII_VIEW.ID_PRODUS, PRODUSE_CATEGORII_VIEW.PRET_PRODUS, PRODUSE_CATEGORII_VIEW.CANTITATE_PRODUS, 
	   PRODUSE_ATRIBUTE_VIEW.NUME_ATRIBUT, PRODUSE_ATRIBUTE_VIEW.ID_ATRIBUT, PRODUSE_ATRIBUTE_VIEW.NUME_CATEGORIE_ATRIBUT, PRODUSE_ATRIBUTE_VIEW.ID_CATEGORIE_ATRIBUT,
	   PRODUSE_ETALOANE_VIEW.NUME_ETALON, PRODUSE_ETALOANE_VIEW.ID_ETALON,
	   PRODUSE_CATEGORII_VIEW.NUME_CATEGORIE, PRODUSE_CATEGORII_VIEW.ID_CATEGORIE,
	   PRODUSE_PRODUCATORI_VIEW.NUME_PRODUCATOR, PRODUSE_PRODUCATORI_VIEW.ID_PRODUCATOR,
	   poze.poza, poze.id, poze.descriere, crc32(rand(1000)) FROM
	   
	PRODUSE_CATEGORII_VIEW 
	
	LEFT JOIN
	
	PRODUSE_ATRIBUTE_VIEW
	
	ON (PRODUSE_CATEGORII_VIEW.ID_PRODUS = PRODUSE_ATRIBUTE_VIEW.ID_PRODUS)
	
	LEFT JOIN
	
	PRODUSE_ETALOANE_VIEW
	
	ON (PRODUSE_CATEGORII_VIEW.ID_PRODUS = PRODUSE_ETALOANE_VIEW.ID_PRODUS)
	
	LEFT JOIN
	
	PRODUSE_PRODUCATORI_VIEW
	
	ON (PRODUSE_CATEGORII_VIEW.ID_PRODUS = PRODUSE_PRODUCATORI_VIEW.ID_PRODUS)
	
	LEFT JOIN
	
	poze
	
	ON (PRODUSE_CATEGORII_VIEW.ID_PRODUS = poze.id_prod);